#!/bin/bash
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

export SHELL=/bin/bash

export PS1='\[\e[1;32m\][\u]\[\e[1;31m\][\h]\[\e[1;35m\][\W]\[\e[0;0m '


# Aliases
alias grep='grep -n --color=auto'
alias l='ls --color=auto'
alias ls='ls --color'
alias ll='ls -la'
alias lll='tree'
alias blue="cd ~ && ./resources/scripts/blue.sh && cd -"
alias joke="cd ~ && ./resources/scripts/joke.sh && cd $OLDPWD"
alias zzz='cmatrix'
alias update='sudo pacman -Syyu'
alias st="git status"
alias pull="git pull --rebase"
alias push="git push"
alias gg="shutdown now"
xset r rate 400 60
eval $(thefuck --alias)

# Print on startup
joke
